SELECT 
	COUNT(O.ORDER_ID) AS QUANTIDADE,
	P.PRODUCT_CATEGORY_NAME AS CATEGORIA_PRODUTO
FROM
	ORDERS O
JOIN
	ORDER_ITEMS OI
ON
	OI.ORDER_ID = O.ORDER_ID
JOIN
	PRODUCTS P
ON
	OI.PRODUCT_ID = P.PRODUCT_ID
WHERE
	ORDER_STATUS = 'canceled'
GROUP BY
	CATEGORIA_PRODUTO
ORDER BY 
	QUANTIDADE DESC
LIMIT 3